### ISSUE TITLE
Angularjs ng-sortable and bootstrap accordion not compatible

### ISSUE THREAD

**Issue by DerekLiang** [a5hik/ng-sortable#187]
As stated in the title.

Error message as the following

Error: [$compile:ctreq] Controller 'asSortableItem', required by directive 'asSortableItemHandle', can't be found!
http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=asSortableItem&p1=asSortableItemHandle
    at REGEX_STRING_REGEXP (https://code.angularjs.org/1.3.15/angular.js:63:12)
    at getControllers (https://code.angularjs.org/1.3.15/angular.js:7583:19)
    at nodeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7772:33)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7117:13)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7120:13)
    at compositeLinkFn (https://code.angularjs.org/1.3.15/angular.js:7120:13)
    at publicLinkFn (https://code.angularjs.org/1.3.15/angular.js:6996:30)
    at $get.boundTranscludeFn (https://code.angularjs.org/1.3.15/angular.js:7135:16)
    at controllersBoundTransclude (https://code.angularjs.org/1.3.15/angular.js:7795:18)
    at link (http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.js:167:37) <h3 class="bct-vertical-bar ng-scope" accordion-heading="">

http://plnkr.co/edit/gwgghRH2UBkPVC0CjOaP

**Comment by a5hik** [comment]
@DerekLiang are you using bootstrap-ui? the module is named similar to the bootstrap ui's sortable module, that could be a reason for the conflict. 'ui.sortable'. Plz change the module name to something else.
I already tried changing this, but it is breaking some prod usages, so i had to revert it back.
Anyways let me try change the master copy, again.

**Comment by DerekLiang** [comment]
http://plnkr.co/edit/VZCFk1C42IgOqyLz8vsB?p=preview

Forked to use the 'as.sortable' instead and it is still not working. See link above.

**Comment by a5hik** [comment]
@DerekLiang you need to place the sortable-item-handle immediate to the sortable-item directive.

Please see the forked plnkr http://plnkr.co/edit/SNrGKWZWBTAM7m2UaR4w?p=preview

Also, If you have to use Drag & Accordion to work together you need to restrict the which part of element is draggable and which is to behave as accordion.

In your example the 'h3' element cannot act as both draggable & accordion.

I would suggest you to write a wrapper element and have both the drag element & accordion element aside. i,e you can add a drag icon for drag behavior.

**Comment by DerekLiang** [comment]
http://plnkr.co/edit/ee1vRST5OUNKNl9UyywK?p=preview

not working as suggested.

**Comment by a5hik** [comment]
@DerekLiang I had some time to make some change to the plnkr sample you given.

http://plnkr.co/edit/eFb15mDqbJW6o6xmT5fY?p=preview

Basically you don't need the accordion directive the show/hide can be achieved by a toggle function.
Please clean up the plnkr sample and you can extend that further.

**Comment by DerekLiang** [comment]
Since there is no easy answer, I will close it since there is an alternative.
