### ISSUE TITLE
package.json: invalid value for 'main'

### ISSUE THREAD

**Issue by hnsr** [a5hik/ng-sortable#191]
The 'main' field in package.json should be a single module id/path to be used as entry point. Currently it is set to an array containing strings that reference the main JS and CSS file, but this means node (or in my case, browserify) fails to load the module:

```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
              ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at tryPackage (module.js:127:23)
    at Function.Module._findPath (module.js:190:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Easiest fix would probably be to set 'main' to a string referencing just the js file, but I'm not sure if other tools depend on 'main' being an array.

As a workaround, I'm currently loading the module with `require('ng-sortable/dist/ng-sortable.js')`

**Comment by crysislinux** [comment]
this problem has been solved by commit 966c8b719205a80b78b0f4bd5cb47e9480721709
